spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: password
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate.ddl-auto: none
#      hibernate.ddl-auto: create
