spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: password
  jpa:
      properties:
        hibernate.show_sql: true
        hibernate.format_sql: false
        hibernate.generate_statistics: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      defer-datasource-initialization: true
      hibernate.ddl-auto: create
      open-in-view: true
  sql.init.mode: always
  