GET http://localhost:8080/patients
Content-Type: application/json

{
    "firstName" : "Paul",
    "lastName": "Dupont",
    "email" : "paul@mail.com",
    "birthDate" : "2000-01-01",
    "address": {
        "street": "Rue des bambous"
    }
}